import { useEffect, useMemo, useState } from 'react'
import './App.css'

const GITHUB_URL = 'https://github.com/slopguard/slopguard'
const API_BASE = import.meta.env.VITE_API_BASE_URL || (import.meta.env.DEV ? 'http://localhost:8000' : '')
const order = { OK: 0, UNKNOWN: 1, REVIEW: 2, RISKY: 3, BLOCK: 4 }
const starter = '# Paste requirements.txt, package.json, source imports, or install commands here.\nrequests>=2.31\nfastapi>=0.110\n'
const signals = [['Phantom declared package', '100'], ['Malicious advisory', '100'], ['Close popular-name typo', '40'], ['Very new package', '15–35'], ['Low downloads', '10–25'], ['No repository link', '15'], ['Install-time script', '20']]
const endpoint = (path) => `${API_BASE}${path}`
const date = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) : 'Not published'
const number = (value) => typeof value === 'number' ? new Intl.NumberFormat().format(value) : 'Not available'

function problem(response, body) {
  if (!response) return { message: 'We could not reach the scanner. Check your connection and try again.' }
  if (response.status === 413) return { message: 'That text is over the 200 KB scan limit. Try a smaller file or excerpt.' }
  if (response.status === 422) return { message: 'We could not understand that request. Check that the text is not empty.' }
  if (response.status === 429) return { message: 'Too many scans from this connection. Please wait and try again.', retry: response.headers.get('Retry-After') }
  if (response.status === 504) return { message: 'The scan took too long. The backend may be busy; try again in a moment.' }
  return { message: body?.detail || 'The scan did not complete. Please try again.' }
}

function Scanner() {
  const [content, setContent] = useState(starter); const [kind, setKind] = useState('auto'); const [samples, setSamples] = useState([])
  const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [waking, setWaking] = useState(false); const [error, setError] = useState(null); const [simple, setSimple] = useState(false)
  useEffect(() => { fetch(endpoint('/api/samples')).then((r) => r.ok ? r.json() : []).then(setSamples).catch(() => {}) }, [])
  async function scan() { setLoading(true); setError(null); setWaking(false); const timer = setTimeout(() => setWaking(true), 4000); try { const response = await fetch(endpoint('/api/scan'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content, kind }) }); const body = await response.json().catch(() => null); if (!response.ok) throw { response, body }; setResult(body) } catch (caught) { setError(problem(caught.response, caught.body)) } finally { clearTimeout(timer); setLoading(false); setWaking(false) } }
  function download() { const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'slopguard-report.json'; link.click(); URL.revokeObjectURL(url) }
  const sorted = useMemo(() => result?.packages ? [...result.packages].sort((a, b) => order[b.verdict] - order[a.verdict] || b.risk - a.risk) : [], [result])
  return <><section className="hero"><div className="eyebrow">Dependency safety, before install</div><h1>AI can invent packages. Attackers can register them. Check before you install.</h1><p>Paste dependency text or code. SlopGuard only checks public package metadata and never installs anything.</p></section><section className="scanner panel" aria-label="Package scanner"><div className="toolbar"><strong>What are you about to install?</strong><label className="hint">Format <select value={kind} onChange={(e) => setKind(e.target.value)}><option value="auto">Auto detect</option><option value="requirements">requirements.txt</option><option value="package_json">package.json</option><option value="python">Python</option><option value="javascript">JavaScript</option><option value="text">Install commands</option></select></label></div>{samples.length > 0 && <div className="sample-row" aria-label="Load a sample">{samples.map((sample) => <button className="sample" key={sample.id} onClick={() => { setContent(sample.content); setKind(sample.kind) }}>{sample.title}</button>)}</div>}<label className="hint" htmlFor="scan-content">Dependency text (not retained)</label><textarea id="scan-content" value={content} onChange={(e) => setContent(e.target.value)} placeholder="Paste dependencies or code…" /><div className="action-row"><label className="hint"><input type="checkbox" checked={simple} onChange={(e) => setSimple(e.target.checked)} /> Explain simply</label><button className="primary" onClick={scan} disabled={loading || !content.trim()}>{loading ? 'Checking packages…' : 'Scan packages'}</button></div>{waking && <p className="notice">Backend is waking up… this first request can take a little longer.</p>}{error && <div className="error" role="alert">{error.message} {error.retry && `Retry in ${error.retry} seconds. `}<button className="copy" onClick={scan}>Try again</button></div>}</section><section aria-live="polite" aria-atomic="true">{loading && <div className="skeleton" aria-label="Scanning packages" />}{!loading && !result && !error && <div className="empty">Your results will appear here. A package that cannot be verified is kept separate from a package that does not exist.</div>}{result && <Results result={result} sorted={sorted} simple={simple} onDownload={download} />}</section></>
}

function Results({ result, sorted, simple, onDownload }) { const counts = result.summary.counts || {}; return <>{result.summary.truncated && <p className="notice">Only the first 60 package references were checked. Narrow the input for complete results.</p>}<div className="summary"><span className="summary-title">Worst result: <span className={`chip ${result.summary.worst_verdict}`}>● {result.summary.worst_verdict}</span></span>{['OK', 'UNKNOWN', 'REVIEW', 'RISKY', 'BLOCK'].map((name) => <span key={name} className={`count ${name}`}>{name} {counts[name] || 0}</span>)}</div><div className="result-list">{sorted.map((item) => <Result item={item} key={`${item.ref.ecosystem}-${item.ref.name}`} simple={simple} />)}</div><button className="secondary download" onClick={onDownload}>Download JSON report</button></> }
function Result({ item, simple }) { const info = item.info || {}; return <article className="card"><div className="result-head"><div><div className="package">{item.ref.name}<span className="ecosystem">{item.ref.ecosystem}</span></div><span className="hint">{item.ref.confidence} from {item.ref.source}</span></div><span className={`chip ${item.verdict}`}>● {item.verdict}</span></div><div className="risk-line" aria-label={`Risk score ${item.risk} out of 100`}><span style={{ width: `${item.risk}%` }} /></div><div className="risk-number">Risk {item.risk}/100 · Trust {item.trust}/100</div>{item.findings?.length ? <ul className="findings">{item.findings.map((finding) => <li key={finding.signal}>{simple ? finding.beginner_message : finding.message}</li>)}</ul> : <p className="muted">No known warning signs were found in public metadata.</p>}{item.alternative && <div className="alternative">Suggested popular name: <b>{item.alternative}</b><button className="copy" onClick={() => navigator.clipboard?.writeText(item.alternative)}>Copy</button></div>}<details><summary>Package details</summary><div className="details-grid"><div><b>First release</b>{date(info.created_at)}</div><div><b>Recent downloads</b>{number(info.downloads)} {info.downloads_period || ''}</div><div><b>Releases</b>{info.release_count ?? 'Not available'}</div><div><b>Source</b>{info.repo_url ? <a href={info.repo_url} target="_blank" rel="noreferrer">Repository</a> : 'Not listed'}</div></div></details></article> }

function Benchmark() { const [data, setData] = useState(null); const [missing, setMissing] = useState(false); useEffect(() => { async function load() { try { let response = await fetch('/summary.json'); if (!response.ok) response = await fetch(endpoint('/api/benchmark')); if (!response.ok) throw Error(); setData(await response.json()) } catch { setMissing(true) } } load() }, []); if (missing) return <section><h1 className="view-title">Benchmark</h1><p className="notice">Benchmark data is not available yet. Run the private benchmark workflow to publish its masked aggregate.</p></section>; if (!data) return <div className="skeleton" aria-label="Loading benchmark" />; const models = Object.entries(data.models || {}); return <section><h1 className="view-title">Slopsquatting benchmark</h1><p className="view-lede">How often dependency-only model replies include unregistered names. Only aggregates and masked names are shown.</p><div className="panel">{models.map(([name, value]) => <div className="bar-row" key={name}><b>{name.replace('_', ' ')}</b><div className="bar"><i style={{ width: `${Math.min(100, (value.phantom_rate || 0) * 100)}%` }} /></div><span>{((value.phantom_rate || 0) * 100).toFixed(1)}%</span></div>)}</div><div className="bench-grid" style={{ marginTop: 18 }}><div className="stat">Repeat across models<b>{((data.phantom_share_across_2_models || 0) * 100).toFixed(1)}%</b></div><div className="stat">Still unregistered<b>{((data.phantom_share_still_unregistered || 0) * 100).toFixed(1)}%</b></div></div><div className="panel" style={{ marginTop: 18 }}><h2>Repeated phantom names</h2>{data.top_repeated_phantoms?.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Masked name</th><th>Occurrences</th></tr></thead><tbody>{data.top_repeated_phantoms.map((row) => <tr key={row.name}><td><code>{row.name}</code></td><td>{row.count}</td></tr>)}</tbody></table></div> : <p className="muted">No repeated phantom names in this published sample.</p>}<div className="note"><b>Methodology:</b> {data.methodology}<br /><b>Limitations:</b> {data.limitations}</div><p className="hint" style={{ marginTop: 14 }}>Generated {date(data.generated_at)}</p></div></section> }

function About() { return <section><h1 className="view-title">How SlopGuard works</h1><p className="view-lede">A conservative check for suspicious package references in AI-written code. It is a decision aid, not a malware verdict.</p><div className="about-grid"><div className="panel"><h2>Deterministic signals</h2><table className="signal-table"><tbody>{signals.map(([signal, points]) => <tr key={signal}><td>{signal}</td><td><b>{points} pts</b></td></tr>)}</tbody></table></div><div className="panel"><h2>Safety and ethics</h2><p className="muted">Registry access is read-only. SlopGuard never installs or executes suggested packages, does not store submitted code, and publishes only masked benchmark phantom names.</p><p><a href={GITHUB_URL} target="_blank" rel="noreferrer">View on GitHub ↗</a></p></div></div><svg className="architecture" viewBox="0 0 760 210" role="img" aria-label="Architecture: text is extracted into package names, checked against registries, then deterministically scored"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#075f87" /></marker></defs>{[['Your text',35],['Extract names',220],['Registry metadata',405],['Deterministic score',590]].map(([label, x]) => <g key={label}><rect x={x} y="70" width="135" height="65" rx="10" fill="var(--surface)" stroke="var(--line)" /><text x={Number(x) + 67} y="108" fill="currentColor" textAnchor="middle" fontSize="15" fontWeight="700">{label}</text></g>)}{[170,355,540].map((x) => <line key={x} x1={x} y1="102" x2={x + 42} y2="102" stroke="#075f87" strokeWidth="2" markerEnd="url(#arrow)" />)}</svg><div className="about-grid"><div className="panel"><h2>CLI</h2><code className="code">slopguard scan requirements.txt --fail-on risky</code></div><div className="panel"><h2>GitHub Action</h2><code className="code">- uses: ./\n  with:\n    fail-on: risky</code></div></div></section> }

function App() { const [view, setView] = useState(() => location.hash.slice(1) || 'scanner'); const [dark, setDark] = useState(() => { try { const saved = localStorage.getItem('slopguard-theme'); return saved ? saved === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches } catch { return matchMedia('(prefers-color-scheme: dark)').matches } }); useEffect(() => { const changed = () => setView(location.hash.slice(1) || 'scanner'); addEventListener('hashchange', changed); return () => removeEventListener('hashchange', changed) }, []); function change(next) { setView(next); window.location.assign(`#${next}`) } function toggle() { const next = !dark; setDark(next); try { localStorage.setItem('slopguard-theme', next ? 'dark' : 'light') } catch { /* Storage can be disabled by browser policy. */ } } return <div className={`app ${dark ? 'dark' : ''}`}><header className="topbar"><div className="shell"><a className="brand" href="#scanner">slop<span>guard</span></a><nav className="nav" aria-label="Main navigation">{['scanner', 'benchmark', 'about'].map((name) => <button key={name} className={view === name ? 'active' : ''} onClick={() => change(name)}>{name[0].toUpperCase() + name.slice(1)}</button>)}</nav><button className="theme" onClick={toggle} aria-label="Toggle colour theme">{dark ? 'Light' : 'Dark'} theme</button></div></header><main className="main shell">{view === 'benchmark' ? <Benchmark /> : view === 'about' ? <About /> : <Scanner />}</main></div> }
export default App
